all:
#g++ -o efl_thread_6 efl_cxx_thread_6.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o entry_cxx_example entry_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o general_funcs_cxx_example general_funcs_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o gengrid_cxx_example gengrid_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o genlist_cxx_example_02 genlist_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o genlist_cxx_example_03 genlist_cxx_example_03.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o hoversel_cxx_example_01 hoversel_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx elementary-cxx` -std=c++11
#g++ -o index_cxx_example_01 index_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o index_cxx_example_02 index_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o inwin_cxx_example inwin_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o map_cxx_example_02 map_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o map_cxx_example_03 map_cxx_example_03.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o glview_cxx_example_01 glview_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o popup_cxx_example_02 popup_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx elementary-cxx` -std=c++11
#g++ -o popup_cxx_example_03 popup_cxx_example_03.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx elementary-cxx` -std=c++11
#g++ -o win_cxx_example win_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o progressbar_cxx_example progressbar_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o slideshow_cxx_example slideshow_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o transit_cxx_example_02 transit_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o transit_cxx_example_03 transit_cxx_example_03.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o transit_cxx_example_04 transit_cxx_example_04.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11	
	g++ -o web_cxx_example_02 web_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas evas-cxx eina-cxx elementary-cxx` -std=c++11
