all:
#g++ -o map_cxx_example_01 map_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o genlist_cxx_example_01 genlist_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o toolbar_cxx_example_01 toolbar_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o toolbar_cxx_example_02 toolbar_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o label_cxx_example_01 label_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina eina-cxx` -std=c++11
#g++ -o calendar_cxx_example_06 calendar_cxx_example_06.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas evas-cxx eina eo` -std=c++11
	g++ -o diskselector_cxx_example_01 diskselector_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas evas-cxx eina eo` -std=c++11
#g++ -o map_cxx_example_01 map_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas evas-cxx eina eo` -std=c++11
#g++ -o map_cxx_example_01 map_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas evas-cxx eina eo` -std=c++11
#g++ -o map_cxx_example_01 map_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas evas-cxx eina eo` -std=c++11
