all:
	g++ -o conformant_cxx_example_01 conformant_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o genlist_cxx_example_01 genlist_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o toolbar_cxx_example_01 toolbar_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o toolbar_cxx_example_02 toolbar_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o colorselector_cxx_example_01 colorselector_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina eina-cxx evas-cxx` -std=c++11
