all:
	g++ -o conformant_cxx_example_01 conformant_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo elementary-cxx` -std=c++11
#g++ -o conformant_cxx_example_02 conformant_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o genlist_cxx_example_01 genlist_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o toolbar_cxx_example_01 toolbar_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o toolbar_cxx_example_02 toolbar_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx evas eina eo` -std=c++11
#g++ -o colorselector_cxx_example_01 colorselector_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina eina-cxx evas-cxx` -std=c++11
#g++ -o ctxpopup_cxx_example_01 ctxpopup_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina eina-cxx evas-cxx` -std=c++11
#g++ -o flip_cxx_example_01 flip_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina eina-cxx evas-cxx` -std=c++11
#g++ -o frame_cxx_example_01 frame_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina eina-cxx evas-cxx` -std=c++11
#g++ -o list_cxx_example_02 list_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o hover_cxx_example_01 hover_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas evas-cxx eina-cxx` -std=c++11
#g++ -o photocam_cxx_example_01 photocam_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o panel_cxx_example_01 panel_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o notify_cxx_example_01 notify_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o panes_cxx_example panes_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o radio_cxx_example_01 radio_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o scroller_cxx_example_01 scroller_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o segment_control_cxx_example segment_control_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o table_cxx_example_01 table_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#edje_cc theme_example.edc && gcc -o theme_example theme_cxx_example_01.cc `pkg-config --libs --cflags elementary ecore ecore-evas evas edje`
#g++ -o theme_cxx_example_01 theme_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx elementary-cxx` -std=c++11
#g++ -o theme_cxx_example_02 theme_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o thumb_cxx_example_01 thumb_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o slider_cxx_example slider_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o notify_cxx_example_01 notify_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o panel_cxx_example_01 panel_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o panes_cxx_example panes_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
