all:

	#g++ searching_quickly.cpp -o searching_quickly -lm -lcrypt -O2 -std=c++11 -pipe -DONLINE_JUDGE `pkg-config --libs --cflags`

	g++ map_searching_quickly.cpp -o map_searching_quickly -lm -lcrypt -O2 -std=c++11 -pipe -DONLINE_JUDGE `pkg-config --libs --cflags`
