all:
#g++ -o fileselector_button_cxx_example fileselector_button_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas evas-cxx eina-cxx` -std=c++11
#g++ -o fileselector_entry_cxx_example fileselector_entry_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o fileselector_cxx_example fileselector_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o flipselector_cxx_example flipselector_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
#g++ -o actionslider_cxx_example_01 actionslider_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11
	g++ -o codegen_cxx_example codegen_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx` -std=c++11 -I/home/luciana/Enlightenment/build/elm/src/examples/
#g++ -o efl_thread_cxx_3 efl_thread_cxx_3.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx` -std=c++11
#g++ -o efl_thread_cxx_4 efl_thread_cxx_4.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx` -std=c++11
#g++ -o efl_thread_cxx_5 efl_thread_cxx_5.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx` -std=c++11
#g++ -o efl_thread_win32_cxx_1 efl_thread_win32_cxx_1.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx` -std=c++11
#g++ -o map_example_cxx_03 map_example_cxx_03.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eo evas eina-cxx evas-cxx` -std=c++11
