all:
#g++ -o evas-init-shutdown_cxx evas-init-shutdown_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags evas evas-cxx eo-cxx eina-cxx efl-cxx` -std=c++11
#g++ -o evas-table_cxx evas-table_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags ecore ecore-evas eo-cxx evas-cxx eina-cxx efl-cxx` -std=c++11
#g++ -o evas-transparent_cxx evas-transparent_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags ecore ecore-evas evas eo-cxx evas-cxx eina-cxx efl-cxx` -std=c++11
#g++ -o evas-box_cxx evas-box_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags ecore ecore-evas evas-cxx eo-cxx eina-cxx efl-cxx` -std=c++11
#g++ -o evas-text_cxx evas-text_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags ecore ecore-evas evas-cxx eo-cxx eina-cxx efl-cxx` -std=c++11
#g++ -o evas-hint_cxx evas-hint_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags ecore ecore-evas evas-cxx eo-cxx eina-cxx efl-cxx` -std=c++11
#g++ -o evas-map-utils_cxx evas-map-utils_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags ecore ecore-evas evas-cxx eo-cxx eina-cxx efl-cxx` -std=c++11
	g++ -o evas-buffer-simple_cxx evas-buffer-simple_cxx.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags evas evas-cxx eo-cxx eina-cxx efl-cxx` -std=c++11
