all:
#g++ -o datetime_cxx_example datetime_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o bg_cxx_example_01 bg_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o bg_cxx_example_02 bg_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o calendar_cxx_example_01 calendar_cxx_example_01.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o calendar_cxx_example_02 calendar_cxx_example_02.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o calendar_cxx_example_03 calendar_cxx_example_03.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o calendar_cxx_example_04 calendar_cxx_example_04.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
#g++ -o calendar_cxx_example_05 calendar_cxx_example_05.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
	g++ -o clock_cxx_example clock_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
	g++ -o datetime_cxx_example datetime_cxx_example.cc -DEFL_BETA_API_SUPPORT=1 -DEFL_EO_API_SUPPORT=1 `pkg-config --libs --cflags elementary eina-cxx eo evas` -std=c++11
