

all:
#gcc -o ecore_evas_1 ecore_evas_1.c `pkg-config --libs --cflags ecore evas ecore-evas`
	gcc -o evas_image_3 evas_image_3.c `pkg-config --libs --cflags ecore evas ecore-evas`
#gcc -o eo_1 eo_1.c `pkg-config --libs --cflags eo ecore evas ecore-evas`
